### ISSUE TITLE
upgrade jade to pug

### ISSUE THREAD

**Issue by alokrajiv** [thekelvinliu/generator-espress#3]
jade is changed to pug now. it would be great it to update it.

**Comment by thekelvinliu** [comment]
thanks for bringing this up! i am aware of the jade to pug rename, and will update this generator once the official release comes out. pug is v2.0.0-beta3 right now, so hopefully it won't be too long! in the meantime, you can always change the package.json, gulpfile, and express config files to use pug instead of jade.
